### PR TITLE
Convert to maven project

### PR DESCRIPTION
**Pull request by johndeverall**

### CODE REVIEW

**Comment by ialoft** [comment]
UP! Thx Perfect John!

**Comment by inblior** [comment]
Any news?

**Comment by johndeverall** [comment]
@ialoft no problem 👍

**Comment by johndeverall** [comment]
@ialoft, @inblior, it seems the maintainers for this are absent? We are happy to adopt this code at TheScene.Co and review all pull requests.

**Comment by callumj** [comment]
Hey guys, happy to transfer ownership to someone who is willing to maintain it.

**Comment by johndeverall** [comment]
Hi Callum, really? Yes, we'd be happy for you to do that. We'll add you as a contributor of course and attribute original authorship. Our organisation on github is `TheSceneCo`

We'll be using this code ourselves for an events guide.

**Comment by callumj** [comment]
@johndeverall Of course! Looks like we need to clear 2 issues to kick off the transfer:

`TheSceneCo/opengraph-java already exists and You don’t have the permission to create repositories on TheSceneCo`

Once those are done I'll give it another shot.

**Comment by johndeverall** [comment]
@callumj awesome, I've cleared out the existing repository (perhaps github may take a while to bring that happen). Hopefully that's enough. If you're using the transfer in the danger area in the settings, you should be able to transfer now.

**Comment by callumj** [comment]
@johndeverall Sadly it looks like I need create permission:

> Transfer this repository to another user or to an organization where you have the ability to create repositories.

**Comment by johndeverall** [comment]
I can arrange write access I think. One more thing though, can you transfer to my user? johndeverall? 

That may be what we've done in the past I think to work around this, as then I can then transfer it on.

**Comment by callumj** [comment]
@johndeverall Sure thing! I'll transfer to yourself.

**Comment by callumj** [comment]
@johndeverall ohndeverall/opengraph-java already exists.

**Comment by johndeverall** [comment]
Ha, it does too, but I just transferred it there :) I'll transfer it back to TheScene.Co, then it should work.

**Comment by johndeverall** [comment]
done, fingers crossed a transfer to johndeverall will work now.

**Comment by callumj** [comment]
@johndeverall Looks like it's pending on your side, have you received the email from GH?

**Comment by johndeverall** [comment]
No, not a thing!

**Comment by callumj** [comment]
@johndeverall 🙌

**Comment by johndeverall** [comment]
@callumj Yeah! So now I should get all pull requests reviewed and merged over the weekend. Thank you Callum and all contributors!

**Comment by CedricReichenbach** [comment]
Congrats on the successful transfer! 😄

Is there an ETA for publishing this module to the central maven repo?

**Pull request merged**
